### PR TITLE
Update jmeter version to 3.x, switch to plugin_manager, other structural changes

### PR DESCRIPTION
**Pull request by wyardley**
See #10 for more details. I apologize in advance for this being such a massive changeset, I couldn't think of a good way to break up the changes.

I have a more or less working version w/ the plugins now.

TODOs (if this gets merged, I can submit additional PRs):

- Would like to get rspec-wait or rspec-retry working, I think this is why testing for tcp port 1099 listening is failing (there's a bit of a delay on startup, I think). I'll leave this test pending for now.
- Run jmeter as non-root user
- Fix logging paths

It looks like the current specinfra works properly w/ Debian services, so I simplified the acceptance tests.

Additionally, for the plugins, it would  be nice to eventually allow you to specify a version in the ensure parameter (as you can with packages). I think this is something better added later as an enhancement, though. And would be nice to drop Puppet < 4  support and switch to some of the newer features, I can take a stab at some of that later.

I was going to leave the existing `class { jmeter::server: }` interface, however, it made it difficult to handle the notifications from the plugins and other config items to the service. So the changes are even more extensive, and some classes are now private, but I think the logic is simplified a bit.

I also made a first pass at docs with puppet strings.

### CODE REVIEW

**Comment by wyardley** [comment]
ps - I'll check on the Ubuntu failure, hadn't tested against ubuntu-1404-x64.

It doesn't look like that's what the workaround in
https://github.com/dduvnjak/puppet-jmeter/blob/master/spec/acceptance/service_spec.rb#L5-L18
was for, in fact, Debian 8 seems to work Ok, so I'll see if that's an actual problem.

**Comment by wyardley** [comment]
I did test manually against Ubuntu 14, and with the stable version, the service ran, and the plugin manager seemed to still work as expected.

**Comment by wyardley** [comment]
@dduvnjak: let me know how this looks if you have a sec to check / test.

I could take out the checksum on the downloads if you think it's better, it does create some extra variables to keep track of and would require more changes to use a non-default download of something (and more work on the part of the user if they don't set checksum to off). But seems like the more secure approach.

**Comment by dduvnjak** [comment]
Thanks @wyardley for the awesome PR! Will push a new version to the Forge shortly.

**Pull request merged**
