### PR TITLE
Increasing Puppet Archive Dependency

### PR DESCRIPTION
**Pull request by ThomasAntoniusCrowley**

### CODE REVIEW

**Comment by Joshua-Snapp** [comment]
I'd like to see this PR get merged and a new version of puppet-jmeter released to Forge. In fact, it looks like this module would run fine with the current Archive module, version 3.2.1. Without this PR and a new version on Forge, librarian-puppet will continue to fail to resolve dependencies when using up to date versions of things like puppet-splunk.

**Comment by ThomasAntoniusCrowley** [comment]
@Joshua-Snapp the puppet-splunk conflict is the exact reason I had to raise this. Would be good to have this merged in.

**Comment by dduvnjak** [comment]
@ThomasAntoniusCrowley thanks for the PR. Will publish to Forge shortly.

**Comment by ThomasAntoniusCrowley** [comment]
@dduvnjak thanks for merging.

**Pull request merged**
